name = input("enter your name:")
age = input("enter your age:")
gender = input("enter your gender:")
city = input("enter your city:")
print("name:",name)
print("age:",age)
print("gender:",gender)
print("city:",city)