numbers = list(map(int, input("Enter numbers: ").split()))
print("Maximum:", max(numbers))
print("Minimum:", min(numbers))
print("Sum:", sum(numbers))
print("Average:", sum(numbers) / len(numbers))
numbers = list(set(numbers))
print("Without Duplicates:", numbers)
print("Even:", [i for i in numbers if i % 2 == 0])
print("Odd :", [i for i in numbers if i % 2 != 0])
print("Ascending :", sorted(numbers))
print("Descending:", sorted(numbers, reverse=True))
value = int(input("Show numbers greater than: "))
print("Filtered:", list(filter(lambda x: x > value, numbers)))